// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFO3wZzV89MfxPW39j4uplUa0QSxHscM',
    appId: '1:634122879163:web:86dc474503ef947fa1299e',
    messagingSenderId: '634122879163',
    projectId: 'aiq-a9d98',
    authDomain: 'aiq-a9d98.firebaseapp.com',
    storageBucket: 'aiq-a9d98.firebasestorage.app',
    measurementId: 'G-P357N830FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZ8qqEjclW9lednDzwbuCbt4uqRAFpAo',
    appId: '1:634122879163:android:693d23b591a27190a1299e',
    messagingSenderId: '634122879163',
    projectId: 'aiq-a9d98',
    storageBucket: 'aiq-a9d98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5FUBo-xHWyB3gSnGXKnIegSYReA-dKJY',
    appId: '1:634122879163:ios:05719daecf50f4bca1299e',
    messagingSenderId: '634122879163',
    projectId: 'aiq-a9d98',
    storageBucket: 'aiq-a9d98.firebasestorage.app',
    iosBundleId: 'com.example.aiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5FUBo-xHWyB3gSnGXKnIegSYReA-dKJY',
    appId: '1:634122879163:ios:05719daecf50f4bca1299e',
    messagingSenderId: '634122879163',
    projectId: 'aiq-a9d98',
    storageBucket: 'aiq-a9d98.firebasestorage.app',
    iosBundleId: 'com.example.aiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFFO3wZzV89MfxPW39j4uplUa0QSxHscM',
    appId: '1:634122879163:web:fb9efcd9a01134b7a1299e',
    messagingSenderId: '634122879163',
    projectId: 'aiq-a9d98',
    authDomain: 'aiq-a9d98.firebaseapp.com',
    storageBucket: 'aiq-a9d98.firebasestorage.app',
    measurementId: 'G-P6N5E2DY4D',
  );
}
